# Generated by Django 4.2.7 on 2023-11-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='1999-04-22'),
            preserve_default=False,
        ),
    ]
